pipeline:
  notify:
    image: pranay91/bobthebuilder:latest
    token: $SPARK_TOKEN
    roomname: "Drone Build Notifications on Spark"
    message: "Build Test successful"
    secrets: [spark_token]
