pipeline:
  ssh:
    image: appleboy/drone-ssh
    host: ec2-35-160-100-109.us-west-2.compute.amazonaws.com
    username: ubuntu
    port: 22
    key: ${ssh_key}
    script:
      - echo test
      - touch testapp
