pipeline:
  ssh:
    image: appleboy/drone-ssh
    host: ubuntu@ec2-35-160-100-109.us-west-2.compute.amazonaws.com
    port: 22
    secrets: [ssh_key]
    key: $ssh_key
    script:
      - echo hello
      - touch testapp
