pipeline:
  ssh:
    image: appleboy/drone-ssh
    host: ubuntu@ec2-35-160-100-109.us-west-2.compute.amazonaws.com
    username: ubuntu
    port: 22
    key_path: ./certs/ubuntu_vm_keypair.pem
    script:
      - echo test
      - touch testapp
    when:
      status: success
