pipeline:
  # build:
  #   image: node:latest
  #   commands:
  #     - npm install
  #     - npm test

  # publish:
  #   image: plugins/docker
  #   repo: ec2-34-211-33-89.us-west-2.compute.amazonaws.com:5000/pranay91/cicd_test_app
  #   insecure: true
  #   registry: ec2-34-211-33-89.us-west-2.compute.amazonaws.com:5000
  #   tags: [1, 1.1, latest]
  #   secrets: [docker_username, docker_password]

  webhook:
    image: pranay91/bobthebuilder
    roomname: "Drone Build Notifications on Spark"
    message: "Build Test successful"
    token: ${SPARK_TOKEN}
    debug: true
    pull: true
    commands:
      - echo $PLUGIN_TOKEN
      - echo $SPARK_TOKEN


  # webhook:
  #   image: cliang2/drone-spark
  #   message: Test123
  #   debug: true
  #   roomName: "Drone Build Notifications on Spark"
  #   auth_token: ${SPARK_TOKEN}
  #   secrets: [spark_token, docker_username, docker_password]
