language: node_js
node_js:
  - "stable"
notifications:
  email:
    on_success: never
    on_failure: never

services:
  - docker

install:
  - docker build -t helloworld .
  - docker run -ti -d -p 3000:3000 --name helloworld helloworld

before_script:
  - npm install jasmine-node

script:
  - docker ps | grep -q helloworld
  - npm test